# Generated by Django 2.2.14 on 2022-04-30 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_patient_forn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='forn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
