# Generated by Django 2.2.14 on 2022-05-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_auto_20220504_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apporval_status',
            field=models.BooleanField(default=False),
        ),
    ]
