# Generated by Django 2.2.14 on 2022-05-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0012_appointment_apporval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emailv',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
